- name: Deploy Docker container to AKS
  hosts: localhost
  gather_facts: false

  vars:
    kubeconfig_path: "./kubeconfig"
    docker_image: "dimario1/log8100_tp3:latest"
    deployment_name: "webgoat"
    service_name: "webgoat-service"

  tasks:
    - name: Login to Azure using service principal
      shell: |
        az login --service-principal \
          --username "{{ lookup('env', 'AZURE_CLIENT_ID') }}" \
          --password "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}" \
          --tenant "{{ lookup('env', 'AZURE_TENANT_ID') }}"
      register: azure_login
      changed_when: false

    - name: Set Azure subscription
      shell: |
        az account set --subscription "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
      register: azure_subscription
      changed_when: false 

    - name: Retrieve kubeconfig for AKS
      command: >
        az aks get-credentials
        --resource-group rg-webgoat
        --name webGoatCluster
        --file "{{ kubeconfig_path }}"
      args:
        creates: "{{ kubeconfig_path }}"

    - name: Create namespace
      kubernetes.core.k8s:
        api_version: v1
        kubeconfig: "{{ kubeconfig_path }}"
        kind: Namespace
        name: webgoat

    - name: Create Kubernetes deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        namespace: webgoat
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ deployment_name }}"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: "{{ deployment_name }}"
            template:
              metadata:
                labels:
                  app: "{{ deployment_name }}"
              spec:
                containers:
                - name: webgoat-container
                  image: "{{ docker_image }}"
                  ports:
                  - containerPort: 8080

    - name: Expose deployment with a LoadBalancer service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        namespace: webgoat
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ service_name }}"
          spec:
            type: LoadBalancer
            selector:
              app: "{{ deployment_name }}"
            ports:
            - protocol: TCP
              port: 80
              targetPort: 8080

    - name: Wait for LoadBalancer to become available
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig_path }}"
        kind: Service
        namespace: webgoat
        name: "{{ service_name }}"
      register: service_info
      until: service_info.resources[0].status.loadBalancer.ingress[0].ip is defined
      retries: 5
      delay: 15

    - name: Print the external IP
      debug:
        msg: "Webgoat is accessible at http://{{ service_info.resources[0].status.loadBalancer.ingress[0].ip }}"
